### ISSUE TITLE
Markers broken with BlueMap 3.20

### ISSUE THREAD

**Issue by RobertRR11** [TechnicJelle/BlueMapOfflinePlayerMarkers#37]
With the newest update of BlueMap the markers are very large and are not in greyscale anymore.

![image](https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers/assets/57044042/c85f4484-d8be-42f7-bdb6-a44e482c6fe1)
(Note: that one greyscale player on the map actually has a greyscale skin)

**Comment by TechnicJelle** [comment]
This is what happens when the custom CSS that this plugin adds to BlueMap doesn't get loaded for some reason.
Are you perhaps hosting your map with an external webserver?
Please tell me more about your general setup, so we can work out how to fix this :)

I have just tested this myself, and it does still work:
![image](https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers/assets/22576047/179d5d71-b9c2-4427-a40b-71df32a7da26)

**Comment by TechnicJelle** [comment]
Plese try going to `http://your.blue.map/assets/bmopm.css`.
You should see something like this:
![image](https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers/assets/22576047/926221ff-34fd-4068-b7c8-c5186587da24)

If you don't, there is a problem in your setup somewhere.

**Comment by RobertRR11** [comment]
going to that url gives me the same CSS
![image](https://github.com/TechnicJelle/BlueMapOfflinePlayerMarkers/assets/57044042/8ef98d65-4cac-414c-94f9-035dd16479f8)

> Please tell me more about your general setup, so we can work out how to fix this :)

I don't really have any special setup and there is no external webserver. The only thing I changed is the webserver port. I also don't have any other BlueMap addon installed.

**Comment by TechnicJelle** [comment]
Hmm... Strange, then...
Could you please join the [BlueMap Discord](https://bluecolo.red/map-discord) and give me a ping `@TechnicJelle` in the `#3rd-party-support` channel?
It'll be easier to talk there :)
